#!/bin/bash

source ./local-env
docker start $DOCKER_CONTAINER
source ./mvnw clean spring-boot:run -Dspring-boot.run.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005"
