
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  flyway:
    sql-migration-prefix: "psql-"
    sql-migration-separator: "__"
    schemas: pl

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://alimmit.auth0.com/

auth0:
  audience: ${AUTH0_API_IDENTIFIER}
